### ISSUE TITLE
Is it worth using functions that mutate?

### ISSUE THREAD

**Issue by scidom** [JuliaStats/Klara.jl#114]
@jrevels, @mlubin, I have noticed that the API of ForwardDiff allows passing a `mutates=true` optional argument to `gradient`. Do you make use of this (for example in some of the optimization Julia packages)? Does it make any substantial difference in performance?

**Comment by mlubin** [comment]
If you're computing the gradient repeatedly in a loop, it's definitely a good idea to use the mutating version.

**Comment by scidom** [comment]
Thanks @mlubin, I agree with your point. I realised that in several cases it is needed to mutate the whole `AllResults` type. In this case, it would not be enough to pass the gradient vector that would be mutated, but also other objects that need to be mutated (same goes when one wants to mutate all higher-order derivatives up to order n). Not sure if we can address this matter at the moment.

In any case, Lora is now connected to ForwardDiff, so I will leave the current issue open for a while longer to ponder potential enchancements.

**Comment by jrevels** [comment]
> I realised that in several cases it is needed to mutate the whole AllResults type.

Not sure if this is what you're referring to, but [ForwardDiff defines mutating "extraction" methods on `ForwardDiffResult`](http://www.juliadiff.org/ForwardDiff.jl/lower_order_results.html#what-you-can-extract-from-a-forwarddiffresult), i.e. the data you ask for (gradient, Hessian, etc.) gets loaded into whatever array you pass to the method.

**Comment by scidom** [comment]
Yes, this link is helpful, thank you @jrevels. The complexity of Lora's code (a parameter can have up to 15 functions related to autodiff) requires that I give it some thought how mutation could be allowed (providing two possible types of input functions, with or without mutation, can complicate the API). I will keep the issue open to think about it in the future. For now ForwardDiff and Lora at least work together.

**Comment by scidom** [comment]
Reminder to self for when I get back to this in the future; the lower-level parameter constructors mutate their corresponding parameter state. This means that I do not need to add an extra layer of API complication for the case of mutating functions. If one really wants to use mutated functions, they can resort to the lower-level implementation of parameters; for this to work with autodiff, I simply have to add a constructor that wraps the functionality of mutated functions for autodiff in conjunction with mutated parameters.

**Comment by scidom** [comment]
Mutation of the result returned by auto-differentiated functions has been allowed in Klara from v0.8.0 onwards, using the relevant API of DiffBase, ReverseDiff and ForwardDiff.
