### ISSUE TITLE
Draw samples from a pdf

### ISSUE THREAD

**Issue by mauro3** [JuliaStats/Klara.jl#153]
I have a probability density function `p(x)`, where `x::Vector{Float64}`, and would like to draw samples from it.  How would I do that?

**Comment by scidom** [comment]
Hi @mauro3, I assume you obviously mean statistically dependent samples using MCMC? Take a look at this script for example, which samples from `plogtarget` (which is an unnormalized Gamma) using Metropolis Hastings:

https://github.com/JuliaStats/Klara.jl/blob/master/doc/examples/Gamma/MH.jl

If you need more help, I will be able to resume Klara development and support in two weeks' time that the academic term is finished.

**Comment by mauro3** [comment]
Yes, using MCMC. I'll study that example.  If I got more questions, I'll report back.  Thanks!
