### ISSUE TITLE
Deprecation warnings for v0.6

### ISSUE THREAD

**Issue by chris-nemeth** [JuliaStats/Klara.jl#162]
Hi Theo,

There seem to be quite a few deprecation warnings with the new Julia v0.6. There don't seem to be any breaking changes and most of the warnings seem to relate to the Array{T}(m) change.

Chris

**Comment by scidom** [comment]
Hi Chris, I fixed most of the issues, you may pull the from the master till a new release is tagged. There are more critical breakages related to the world age introduced in Julia v0.6, which I am not sure I know how to fix, I will try.

**Comment by scidom** [comment]
Chris, I have retrieved about 90% of the functionality. There are two issues remaining to be solved: i) one is related to the new "where" keyword, which affects a lower triangular type def that in turn affects SMMALA and RAM, ii) the world age issue that affects a `mark()` function, which is not the most frequently used routine of the package. All the other samplers, as well as autodiff work if you checkout the latest commit (reverse autodiff has become very fast compare to previous versions of the ReverseDiff package).
