### ISSUE TITLE
World age issue due to code generation inside an inner constructor

### ISSUE THREAD

**Issue by scidom** [JuliaStats/Klara.jl#163]
@JeffBezanson, @tkelman, @ararslan
I get a world age error in Julia v0.6 related to the fact that I code-generate two functions from inside an inner constructor [here](https://github.com/JuliaStats/Klara.jl/blob/master/src/iostreams/ParameterIOStreams/BasicContParamIOStream.jl#L49); this used to work in Julia v0.5. Is there an easy fix for this problem?

**Comment by tkelman** [comment]
Please use discourse instead of pinging people.

**Comment by scidom** [comment]
Sure, thanks for your support @tkelman.
