### ISSUE TITLE
Issue related to where keyword and parametric types

### ISSUE THREAD

**Issue by scidom** [JuliaStats/Klara.jl#164]
@andreasnoack, @numfocus

The following typealias used to work in Julia v0.5:

```
typealias RealLowerTriangular{T<:Real, S<:AbstractMatrix} LowerTriangular{T, S}
```

Upon upgrading to Julia v0.6, I received a suggestion on the REPL to use instead the following:

```
RealLowerTriangular{T<:Real, S<:AbstractMatrix} = LowerTriangular{T, S}
```

However, upon trying the supposed fix, I get the following error:

```
julia> Klara.RealLowerTriangular(ones(2))
ERROR: MethodError: Cannot `convert` an object of type Array{Float64,1} to an object of type LowerTriangular{T,S} where S<:(AbstractArray{T,2} where T) where T<:Real
This may have arisen from a call to the constructor LowerTriangular{T,S} where S<:(AbstractArray{T,2} where T) where T<:Real(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] LowerTriangular{T,S} where S<:(AbstractArray{T,2} where T) where T<:Real(::Array{Float64,1}) at ./sysimg.jl:24
```

Do you know how I could fix this problem?

**Comment by andreasnoack** [comment]
ones(2) is a Vector. Did that use to work? What if you input ones(2,2)?

**Comment by scidom** [comment]
Sorry about this @andreasnoack, was meant to say `ones(2, 2)` indeed, which gives the following error:

```
julia> Klara.RealLowerTriangular(ones(2, 2))
ERROR: MethodError: Cannot `convert` an object of type Array{Float64,2} to an object of type LowerTriangular{T,S} where S<:(AbstractArray{T,2} where T) where T<:Real
This may have arisen from a call to the constructor LowerTriangular{T,S} where S<:(AbstractArray{T,2} where T) where T<:Real(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] LowerTriangular{T,S} where S<:(AbstractArray{T,2} where T) where T<:Real(::Array{Float64,2}) at ./sysimg.jl:24
```

Yes, the initial definition used to work with Julia v0.5.2.

**Comment by andreasnoack** [comment]
Please ask the question on Discourse

**Comment by scidom** [comment]
Thanks Andreas, will do.

**Comment by ararslan** [comment]
Out of curiosity, who were you trying to contact by pinging the NumFOCUS organization, `@numfocus`?

**Comment by scidom** [comment]
oh, this was a mistake, I was actually meant to write to you @ararslan, and mixed up the nicknames.

**Comment by scidom** [comment]
I did this elsewhere too, in one more issue, sorry about this, will change it to your username there too @ararslan.
