### ISSUE TITLE
ForwardDiff 0.4 0.6

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaStats/Klara.jl#171]
REQUIRE 
ForwardDiff 0.4 0.6
is causing issuee.

are you going to accept latest ForwardDiff?

**Comment by scidom** [comment]
ForwardDiff v0.6 brings breaking changes. This means the upgrade is non-trivial due to having to change Klara's at various points, ranging from DiffResults, to DiffConfig etc. I made a start today. It will take some time to finish, given work commitments.

**Comment by montyvesselinov** [comment]
I understand. SInce we are using Klara we also cannot adopt the
ForwardDiff changes.

-monty

**Comment by scidom** [comment]
I will do my best to complete within the next week or so.

**Comment by papamarkou** [comment]
I made Klara work with the newer version of ForwardDiff. The new version of Klara has been pushed to METADATA, awaiting to be merged.
