### ISSUE TITLE
Logistic Regression example does not work anymore

### ISSUE THREAD

**Issue by vollmersj** [JuliaStats/Klara.jl#79]
It would be great if the following could be fixed:
The line 

``` jl
model(ex, vars=zeros(nbeta), gradient=true)
```

in `logistic_regression.jl` yields the following error:

``` jl
MCMC not defined
in generateModelFunction at modelparser.jl:38
in MCLikelihood at MCLikelihood.jl:86
in model at models.jl:26
```

Any comments are appreciated.

[@jiahao - add code quotes]

**Comment by scidom** [comment]
Thanks @vollmersj, I will check if there is a quick fix tonight, otherwise bear with me for 3-4 weeks before a (relatively massive) package upgrade being in the works in one of the dev branches.

**Comment by scidom** [comment]
There are several examples of how to run logistic regression at

https://github.com/JuliaStats/Klara.jl/tree/master/doc/examples/swiss

I will open a separate issue about creating a high-level DSL to achieve the same result.
